Update run

diff --git a/s2i-dockerfile/run b/s2i-dockerfile/run
--- a/s2i-dockerfile/run
+++ b/s2i-dockerfile/run
@@ -47,15 +47,18 @@ ibmcloud ce build create -n s2i-dbuild -i "$ICR/${ICR_NS}/app" --rs s2i-dicr \
 ibmcloud ce buildrun submit -n s2i-drun --build s2i-dbuild --wait
 
 # Test the image we just built - deploy an app and 'curl' it
-ibmcloud ce app create -n s2i-dockerfile --image "$ICR/${ICR_NS}/app" --rs s2i-dicr
-URL=$(ibmcloud ce app get -n s2i-dockerfile -o url)
-curl -fs "${URL}" | tee out
-[[ "${PIPESTATUS[0]}" == "0" ]]
+# ibmcloud ce app create -n s2i-dockerfile --image "$ICR/${ICR_NS}/app" --rs s2i-dicr
+# URL=$(ibmcloud ce app get -n s2i-dockerfile -o url)
+# curl -fs "${URL}" | tee out
+# [[ "${PIPESTATUS[0]}" == "0" ]]
+# 
+# if ! grep "I was built"  out > /dev/null ; then
+#   echo "Missing expected outout"
+#   exit 1
+# fi
 
-if ! grep "I was built"  out > /dev/null ; then
-  echo "Missing expected outout"
-  exit 1
-fi
+# Test the image we just built - deploy an app and 'curl' it
+# ibmcloud ce job create -n s2i-dockerfile --image "$ICR/${ICR_NS}/app" --rs s2i-dicr
 
 # Clean
 clean
